### PR TITLE
Stream chat tibble

### PR DESCRIPTION
**Pull request by JamesHWade**
- Stream chat now returns a `chat_tibble` class (#21).
- Fixed a bug with `chat()` trying to create a tibble with empty `tool_calls` column.

### CODE REVIEW

**Comment by JamesHWade** [comment]
Implemented a `...` input from `chat()` and `stream()`. This sticks with a chat_tibble output, which is different from #23. Not sure which you prefer @romainfrancois.

**Comment by romainfrancois** [comment]
I *think* having `...` in the main function is not that great after all. I'll rework #23 so that `chat()` takes a single argument called `messages` as in the API, and then we can have a set of building functions to make `messages`. 

It's a little bit less magical ✨, but I think that's the right balance. 

I also *think* I agree with you that the `tibble` output was the right call. One of the goals of #23 was to not lose the inputs, but perhaps we can organize the `tibble` so that it has both inputs and outputs. 

```r
msgs <- chat("you are a weather reporter. in the following messages, I'll give you a city and you give back a weather report. Ready ?")
chat(messages(msgs, "Montpellier, France"))
chat(messages(msgs, "San Francisco"))
```

It's important here that we retain the original `prompt`. 

I'll play some more on #23

**Comment by romainfrancois** [comment]
I changed a few things in #26 I can take the spirit of this PR and adjust it

**Comment by JamesHWade** [comment]
Okay, I'll close this one then. Happy to see the continued progress! It's shaping up nicely.

**Pull request closed without merging**
